language: php

php:
  - 8.0
  - 8.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_VERSION=3.4.*

matrix:
  include:
    - php: 8.0
      env: SYMFONY_VERSION=^5.4
    - php: 8.1
      env: SYMFONY_VERSION=^5.4

before_install:
  - composer self-update
  - if [ "$COMPOSER_FLAGS" == "--prefer-lowest" ]; then composer require "roave/security-advisories" dev-master --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
